# Generated by Django 2.2.1 on 2019-06-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_by', models.ForeignKey(on_delete='SET_NULL', related_name='books_uploaded', to='book_app.User')),
                ('users_who_like', models.ManyToManyField(related_name='liked_books', to='book_app.User')),
            ],
        ),
    ]
